# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multimodal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'multimodal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10multimodal.proto\x12\nmultimodal\"-\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"\x1d\n\x0c\x41udioRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\'\n\x08Response\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\x32\x93\x01\n\x11MultiModalService\x12>\n\x0cProcessFrame\x12\x18.multimodal.FrameRequest\x1a\x14.multimodal.Response\x12>\n\x0cProcessVoice\x12\x18.multimodal.AudioRequest\x1a\x14.multimodal.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multimodal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=32
  _globals['_FRAMEREQUEST']._serialized_end=77
  _globals['_AUDIOREQUEST']._serialized_start=79
  _globals['_AUDIOREQUEST']._serialized_end=108
  _globals['_RESPONSE']._serialized_start=110
  _globals['_RESPONSE']._serialized_end=149
  _globals['_MULTIMODALSERVICE']._serialized_start=152
  _globals['_MULTIMODALSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
